# Generated by Django 5.1.1 on 2024-09-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
